dist: xenial

language: python

cache: pip

python:
    - "3.5"
    - "3.6"
    - "3.7"

addons:
  apt:
    packages:
      - libhdf5-dev
      - libnetcdf-dev

before_install:
  - pip install -U pytest pytest-cov h5py netCDF4 vtk requests lxml

install:
  - pip install .

script:
  - cd test/ && pytest --cov meshio

after_success:
  - bash <(curl -s https://codecov.io/bash)
